name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3.1
  - plyfile=0.8.1
  - python=3.7.13
  - pip=22.3.1
  - pytorch=1.11.0
  - torchaudio=0.11.0
  - torchvision=0.12.0
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
